oslo_messaging._drivers.common [req-5233acf0-9fb1-4684-9bc9-807fdd6404b7 ] ['Traceback (most recent call last):\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply\n executor_callback))\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch\n executor_callback)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch\n result = func(ctxt, **new_args)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/nova/network/manager.py", line 1914, in delete_network\n network.destroy()\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/nova/objects/base.py", line 189, in wrapper\n ctxt, self, fn.__name__, args, kwargs)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/nova/conductor/rpcapi.py", line 395, in object_action\n objmethod=objmethod, args=args, kwargs=kwargs)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/client.py", line 156, in call\n retry=self.retry)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/transport.py", line 90, in _send\n timeout=timeout, retry=retry)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 417, in send\n retry=retry)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 408, in _send\n raise result\n', 'NetworkInUse_Remote: Network 11 is still in use.\nTraceback (most recent call last):\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/conductor/manager.py", line 410, in _object_dispatch\n return getattr(target, method)(context, *args, **kwargs)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/objects/base.py", line 204, in wrapper\n return fn(self, ctxt, *args, **kwargs)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/objects/network.py", line 183, in destroy\n db.network_delete_safe(context, self.id)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/db/api.py", line 1042, in network_delete_safe\n return IMPL.network_delete_safe(context, network_id)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/db/sqlalchemy/api.py", line 129, in wrapper\n return f(*args, **kwargs)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/db/sqlalchemy/api.py", line 3387, in network_delete_safe\n raise exception.NetworkInUse(network_id=network_id)\n\nNetworkInUse: Network 11 is still in use.\n\n']
oslo_messaging._drivers.common [req-1845347c-b64e-4f09-a59b-bb6c30bae5bd ] ['Traceback (most recent call last):\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply\n executor_callback))\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch\n executor_callback)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch\n result = func(ctxt, **new_args)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/nova/network/manager.py", line 1914, in delete_network\n network.destroy()\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/nova/objects/base.py", line 189, in wrapper\n ctxt, self, fn.__name__, args, kwargs)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/nova/conductor/rpcapi.py", line 395, in object_action\n objmethod=objmethod, args=args, kwargs=kwargs)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/rpc/client.py", line 156, in call\n retry=self.retry)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/transport.py", line 90, in _send\n timeout=timeout, retry=retry)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 417, in send\n retry=retry)\n', ' File "/opt/pf9/nova/lib/python2.6/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 408, in _send\n raise result\n', 'NetworkInUse_Remote: Network 42 is still in use.\nTraceback (most recent call last):\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/conductor/manager.py", line 410, in _object_dispatch\n return getattr(target, method)(context, *args, **kwargs)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/objects/base.py", line 204, in wrapper\n return fn(self, ctxt, *args, **kwargs)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/objects/network.py", line 183, in destroy\n db.network_delete_safe(context, self.id)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/db/api.py", line 1042, in network_delete_safe\n return IMPL.network_delete_safe(context, network_id)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/db/sqlalchemy/api.py", line 129, in wrapper\n return f(*args, **kwargs)\n\n File "/opt/pf9/nova/lib/python2.6/site-packages/nova/db/sqlalchemy/api.py", line 3387, in network_delete_safe\n raise exception.NetworkInUse(network_id=network_id)\n\nNetworkInUse: Network 42 is still in use.\n\n']
[bbmaster][Thread-1] Received: {u'opcode': u'status', u'data': {u'status': u'failed', u'info': {u'arch': u'x86_64', u'hostname': u'platform9-vmware-gateway', u'os_family': u'Linux', u'os_info': u'centos 6.6 Final'}, u'hypervisor_info': {u'hypervisor_type': u'VMWareCluster'}, u'timestamp': u'2015-12-22 09:11:58.760325', u'apps': {u'pf9-vmw-mgmt': {u'config': {}, u'version': u'1.0.0-101', u'service_states': {}}, u'pf9-cindervolume': {u'running': True, u'version': u'1.3.0-199', u'config': {u'cinder': {u'DEFAULT': {u'volumes_dir': u'/opt/pf9/etc/pf9-cindervolume/volumes/', u'rootwrap_config': u'/opt/pf9/etc/pf9-cindervolume/rootwrap.conf', u'ec2_dmz_host': u'localhost', u'notification_driver': u'messaging', u'lock_path': u'/tmp/', u'state_path': u'/opt/pf9/pf9-cindervolume/lib/python2.6/site-packages/cinder', u'debug': u'True', u'host': u'0cb18239-1e6e-49cf-b599-e049661975c5', u'volume_group': u'cinder-volumes', u'publish_errors': u'True', u's3_host': u'localhost', u'auth_strategy': u'keystone', u'rpc_backend': u'rabbit'}, u'oslo_messaging_rabbit': {u'rabbit_userid': u'7uzmRL2NoCF3rmFJ', u'rabbit_port': u'5673', u'rabbit_use_ssl': u'False', u'rabbit_host': u'localhost', u'rabbit_password': u'QuY2l6Tv3vVfFIg4'}, u'spice': {u'html5proxy_base_url': u'http://localhost:6082/spice_auto.html'}, u'keystone_authtoken': {u'admin_user': u'cinder', u'admin_tenant_name': u'services', u'auth_port': u'35357', u'auth_protocol': u'http', u'admin_password': u'9t1d9I2sRcDMf9ZT', u'auth_host': u'localhost'}, u'database': {u'connection': u'mysql://cinder:tlM79HfEyYTW0J0w@127.0.0.1/cinder'}}}}, u'pf9-ceilometer': {u'config': {u'ceilometer': {u'DEFAULT': {u'host': u'0cb18239-1e6e-49cf-b599-e049661975c5', u'hypervisor_inspector': u'vsphere'}, u'keystone_authtoken': {u'admin_user': u'ceilometer', u'admin_tenant_name': u'services', u'admin_password': u'o29g3KqYON0iCBPz'}, u'service_credentials': {u'os_password': u'o29g3KqYON0iCBPz', u'os_auth_url': u'https://blackboard.platform9.net/keystone_admin/v2.0/', u'os_username': u'ceilometer', u'os_tenant_name': u'services'}}}, u'version': u'1.4.0-210', u'service_states': {u'pf9-ceilometer': True}}, u'pf9-comms': {u'running': True, u'version': u'1.4.0-200.8626a9f', u'config': {}}, u'pf9-ostackhost': {u'config': {u'nova': {u'DEFAULT': {u'rabbit_userid': u'NhGdmkdE3WvoJnNq', u'firewall_driver': u'nova.virt.libvirt.firewall.IptablesFirewallDriver', u'rabbit_host': u'localhost', u'ec2_dmz_host': u'localhost', u'instances_path': u'/opt/pf9/data/instances/', u'force_config_drive': u'always', u'rabbit_password': u'1GHZtPUHMmEYISlR', u'host': u'0cb18239-1e6e-49cf-b599-e049661975c5', u'xvpvncproxy_base_url': u'http://localhost:6081/console', u's3_host': u'localhost', u'compute_driver': u'vmwareapi.VMwareVCDriver', u'flat_interface': u'eth0', u'novncproxy_base_url': u'http://localhost:6080/vnc_auto.html'}, u'libvirt': {u'inject_partition': u'-1'}, u'PF9': {u'ignore_folders': u'pf9_cinder_volumes'}, u'workarounds': {u'destroy_after_evacuate': u'False'}, u'vmware': {u'cluster_name': u'fgtd-tr1-c01,fgtd-tr1-c02,mgmt', u'datastore_regex': u'bbl_nfs_prd_trcl1va2_vmdkos01,vmtemplates,fg_tr02b_va2_vmdk_os,bbl_nfs_prd_trcl1va2_vmdkos02,fg_tr02b_va2_vmdk_mgmt', u'task_poll_interval': u'2'}, u'spice': {u'html5proxy_base_url': u'http://localhost:6082/spice_auto.html'}}}, u'version': u'1.4.0-1837', u'service_states': {u'pf9-ostackhost': False, u'pf9-novncproxy': True}}}, u'desired_apps': {u'pf9-vmw-mgmt': {u'url': u'%(download_protocol)s://%(host_relative_amqp_fqdn)s:%(download_port)s/private/pf9-vmw-mgmt-1.0.0-101.x86_64.rpm', u'service_states': {}, u'version': u'1.0.0-101', u'config': {}}, u'pf9-ostackhost': {u'url': u'%(download_protocol)s://%(host_relative_amqp_fqdn)s:%(download_port)s/private/pf9-ostackhost-1.4.0-1837.x86_64.rpm', u'service_states': {u'pf9-ostackhost': True, u'pf9-novncproxy': True}, u'version': u'1.4.0-1837', u'config': {u'nova': {u'DEFAULT': {u'rabbit_userid': u'NhGdmkdE3WvoJnNq', u'rabbit_host': u'localhost', u'ec2_dmz_host': u'localhost', u'instances_path': u'/opt/pf9/data/in}
[bbmaster][Thread-1] Received: {u'opcode': u'status', u'data': {u'status': u'failed', u'info': {u'arch': u'x86_64', u'hostname': u'p9host-01.dc1.rhythmic.local', u'os_family': u'Linux', u'os_info': u'centos 7.1.1503 Core'}, u'hypervisor_info': {u'hypervisor_type': u'kvm'}, u'timestamp': u'2015-12-22 09:11:41.489811', u'apps': {u'pf9-neutron-base': {u'config': {}, u'version': u'1.3.0-71', u'service_states': {}}, u'pf9-comms': {u'running': True, u'version': u'1.4.0-200.8626a9f', u'config': {}}, u'pf9-neutron-metadata-agent': {u'config': {u'metadata_conf': {u'DEFAULT': {u'admin_user': u'neutron', u'metadata_proxy_shared_secret': u'ZsUUOW5iZKVWcirn', u'admin_tenant_name': u'services', u'auth_region': u'RegionOne', u'auth_url': u'http://localhost:8080/keystone', u'admin_password': u'HGhjcRcieGeMQ9fQ', u'nova_metadata_ip': u'localhost'}}, u'neutron_conf': {u'DEFAULT': {u'rabbit_userid': u'sJarlAEahBOHgucV', u'rabbit_port': u'5673', u'host': u'052f2a2b-91fd-46a7-addf-5938f11f1ed5', u'state_path': u'/var/opt/pf9/neutron', u'rabbit_password': u'vRqb1vnLUar4WhRO'}, u'keystone_authtoken': {u'identity_uri': u'http://localhost:8080/keystone_admin', u'admin_tenant_name': u'services', u'admin_password': u'HGhjcRcieGeMQ9fQ', u'admin_user': u'neutron', u'auth_uri': u'http://localhost:8080/keystone'}}}, u'version': u'1.3.0-71', u'service_states': {u'pf9-neutron-metadata-agent': True}}, u'pf9-neutron-dhcp-agent': {u'config': {u'neutron_conf': {u'DEFAULT': {u'rabbit_userid': u'FHbGiBWdZa0XetE2', u'rabbit_port': u'5673', u'host': u'052f2a2b-91fd-46a7-addf-5938f11f1ed5', u'state_path': u'/var/opt/pf9/neutron', u'rabbit_password': u'iHqjDZIfR62EUlsY'}, u'keystone_authtoken': {u'identity_uri': u'http://localhost:8080/keystone_admin', u'admin_tenant_name': u'services', u'admin_password': u'HGhjcRcieGeMQ9fQ', u'admin_user': u'neutron', u'auth_uri': u'http://localhost:8080/keystone'}}, u'dhcp_conf': {u'DEFAULT': {u'dhcp_delete_namespaces': u'True', u'interface_driver': u'neutron.agent.linux.interface.OVSInterfaceDriver'}}}, u'version': u'1.3.0-71', u'service_states': {u'pf9-neutron-dhcp-agent': True}}, u'pf9-ceilometer': {u'config': {u'ceilometer': {u'DEFAULT': {u'host': u'052f2a2b-91fd-46a7-addf-5938f11f1ed5', u'hypervisor_inspector': u'libvirt'}, u'keystone_authtoken': {u'admin_user': u'ceilometer', u'admin_tenant_name': u'services', u'admin_password': u'Cgs7Q2ogLjWOSYOb'}, u'service_credentials': {u'os_password': u'Cgs7Q2ogLjWOSYOb', u'os_auth_url': u'https://rhythmic.platform9.net/keystone_admin/v2.0/', u'os_username': u'ceilometer', u'os_tenant_name': u'services'}}}, u'version': u'1.4.0-210', u'service_states': {u'pf9-ceilometer': True}}, u'pf9-neutron-l3-agent': {u'config': {u'neutron_conf': {u'DEFAULT': {u'rabbit_userid': u'6ULcfA84lAmwOufR', u'rabbit_port': u'5673', u'host': u'052f2a2b-91fd-46a7-addf-5938f11f1ed5', u'state_path': u'/var/opt/pf9/neutron', u'rabbit_password': u'MnyLETi1SLlzJxGK'}, u'keystone_authtoken': {u'identity_uri': u'http://localhost:8080/keystone_admin', u'admin_tenant_name': u'services', u'admin_password': u'HGhjcRcieGeMQ9fQ', u'admin_user': u'neutron', u'auth_uri': u'http://localhost:8080/keystone'}}, u'l3_conf': {u'DEFAULT': {u'external_network_bridge': u'br-ex', u'router_delete_namespaces': u'True', u'use_namespaces': u'True', u'interface_driver': u'neutron.agent.linux.interface.OVSInterfaceDriver'}}}, u'version': u'1.3.0-71', u'service_states': {u'pf9-neutron-l3-agent': False}}, u'pf9-ostackhost': {u'config': {u'nova': {u'DEFAULT': {u'rabbit_userid': u'iNo1eiX3iLBk9MkM', u'connection_type': u'libvirt', u'firewall_driver': u'nova.virt.firewall.NoopFirewallDriver', u'report_interval': u'60', u'rabbit_host': u'localhost', u'ec2_dmz_host': u'localhost', u'linuxnet_interface_driver': u'nova.network.linux_net.LinuxOVSInterfaceDriver', u'network_api_class': u'nova.network.neutronv2.api.API', u'instances_path': u'/opt/pf9/data/instances/', u'security_group_api': u'neutron', u'rabbit_password': u'BNl3a7q7cASCly7g', u'host': u'052f2a2b-91fd-46a7-addf-5938f11f1ed5', u'xvpvncproxy_base_url': u'ht}